### ISSUE TITLE
Release 1.0.1 require macOS 13.3 or later

### ISSUE THREAD

**Issue by atriwidada** [ishaanbedi/Voyager#1]
Tried to run Voyager 1.0.1 on macOS 12.7.2 but failed with this error message:
**You can't use this version of "Voyager" with this version of macOS.**
You have macOS 12.7.2. The application require macOS 13.3 or later.

![Screen Shot 2024-01-21 at 09 33 30](https://github.com/ishaanbedi/Voyager/assets/1826702/17b19e69-52c5-44f3-ab6c-f6e0b8a6a4c3)

While [this post](https://www.ishaanbedi.in/posts/voyager) said:

> 1. Requirements
Before you set sail, ensure you have macOS 11.0 or later installed on your Mac.

**Comment by ishaanbedi** [comment]
Hey! 
Thanks for bringing this up. 
Let me check this and I'll get back to you!

**Comment by ishaanbedi** [comment]
Hey @atriwidada !
I've fixed some issues that caused this, and now Voyager can be installed on macOS 12.0 or higher.
Can you please give it a shot to the latest DMG file [here](https://github.com/ishaanbedi/Voyager/releases)?

Further, I can take it to work on macOS 11.0 and higher as well, but it will require some more refactoring and changing some modifiers. I'll work on it as well in the next release!

**Comment by atriwidada** [comment]
I can run it now. Thanks!
